number_1 = int(input("please enter a number: "))
number_2 = int(input("please enter a number: "))
number_3 = int(input("please enter a number: "))

print(number_1 * number_2)
print(number_1 * number_3)
print(number_1 / number_2)
print(number_1 / number_3)
print(number_1 + number_2)
print(number_1 + number_3)
print(number_1 - number_2)
print(number_1 - number_3)

print(number_2 * number_1)
print(number_2 * number_3)
print(number_2 / number_1)
print(number_2 / number_3)
print(number_2 + number_1)
print(number_2 + number_3)
print(number_2 - number_1)
print(number_2 - number_3)

print(number_3 * number_2)
print(number_3 * number_1)
print(number_3 / number_2)
print(number_3 / number_1)
print(number_3 + number_2)
print(number_3 + number_1)
print(number_3 - number_2)
print(number_3 - number_1)